version: '3.5'
volumes:
  oracle:
services:
  db:
    image: gvenzl/oracle-xe:21.0.3
    container_name: oracle-xe-21
    restart: always
    environment:
      ORACLE_PASSWORD: 789789
      ORACLE_DATABASE: test
      APP_USER: luciano
      APP_USER_PASSWORD: 789789
    volumes:
      - oracle:/var/lib/oracle
    ports:
      - "1521:1521"